---
- name: Manage subnet into vNet
  hosts: localhost
  tasks:
        
  - name: Attach NSG to existing  subnet
    azure_rm_subnet:
      resource_group: ansiblelab4amelie
      virtual_network_name : dmz
      name: httpapp
      security_group:
        name: httpd-nsg-app1