---
- name: Attach HTTP NSG to existing subnet
  hosts: localhost
  tasks:
        
  - name: Attach NSG to existing  subnet
    azure_rm_subnet:
      resource_group: "{{ myResourceGroup }}"
      virtual_network_name: "{{ myvnetname }}"
      name: "{{ mysubnetname }}"
      security_group:
        name: "{{ mysecgroup }}"