---
- name: Test WEB Site
  hosts: "{{ vm_name }}"
  gather_facts: true
  tasks:
    - name: Check that a page returns successfully but fail if the word Demo is not in the page contents
      ansible.builtin.uri:
        url: http://{{ ansible_host }}
        return_content: true
      register: this
      failed_when: "'Demo' not in this.content"
