---
- name: Using Azure collection Virtual network
  hosts: localhost
  tasks:
        
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ myvnetname }}"
      address_prefixes_cidr: "{{ vnet_subnet }}/{{ vnet_ mask }}"
    register: address_prefixes_cidr

  - debug:
      var: address_prefixes_cidr