---
- name: Create NSG
  hosts: localhost
  tasks:
    
  # Create a security group
  - azure_rm_securitygroup:
        resource_group: "{{ myResourceGroup }}"
        name: "{{ mysecgroup }}"
        purge_rules: yes
        rules:
            - name: DenySSH
              protocol: Tcp
              destination_port_range: 22
              access: Deny
              priority: 100
              direction: Inbound
            - name: 'AllowSSH'
              protocol: Tcp
              source_address_prefix:
                - '70.52.103.0/24'
                - '70.52.103.0/24'
              destination_port_range: 22
              access: Allow
              priority: 101
              direction: Inbound
            - name: 'AllowMultiplePorts'
              protocol: Tcp
              source_address_prefix:
                - '70.52.103.0/24'
                - '70.52.103.0/24'
              destination_port_range:
                - 80
                - 443
              access: Allow
              priority: 102