---
- name: Using Azure collection
  hosts: localhost
  tasks:
      
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: ansiblelab4amelie
      name: testvm10
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      image:
        offer: CentOS 8.3 Free
        publisher: Cognosys
        sku: '8.3'
        version: latest