---
- name: Using Azure collection
  hosts: localhost
  tasks:
      
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: {{ myResourceGroup }}
      name: testvm10
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      image:
        offer: RHEL
        publisher: RedHat
        sku: '7-LVM'
        version: latest
      vm_size: Standard_D4_v2