---
- name: Using Azure collection
  hosts: localhost
  tasks:
      
  - name: Create Windows VM with defaults
    azure_rm_virtualmachine:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ vm_name }}"
      short_hostname: "{{ vm_name }}"      
      admin_username: "{{ username }}"
      admin_password: "{{ password }}"
      network_interfaces: nic
      os_type: Windows
      virtual_network_name: "{{ myvnetname }}"
      subnet_name: "{{ mysubnetname }}"
      open_ports:
        - '3389'
        - '80'
        - '443'
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2019-Datacenter'
        version: latest
      vm_size: Standard_B1s      
