---
- name: Using Azure collection
  hosts: localhost
  tasks:
        
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: {{ myResourceGroup }}
      name: testvn001-ansible
      address_prefixes: "10.20.0.0/24"