---
- name: Using Azure collection Virtual network
  hosts: localhost
  tasks:
        
  - name: Get instance of Policy
    azure_rm_devtestlabpolicy_info:
      resource_group: "{{ myResourceGroup }}"
      lab_name: myLab
      policy_set_name: myPolicySet
      name: myPolicy
      tags:
        - key:value
