---
- name: Using Azure collection Virtual network
  hosts: localhost
  tasks:
        
  - name: Destroy a virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ myvnetname }}"
      state: absent