---
- name: Using Azure collection Virtual network
  hosts: localhost
  tasks:
          
  - name: Run basic PowerShell script
    ansible.windows.win_powershell:
      script: |
        echo "Hello World"