---
- name: Using Azure collection
  hosts: localhost
  tasks:
        
  - name: Get facts of specific subnet
    azure_rm_subnet_info:
      resource_group: "{{ myResourceGroup }}"
      virtual_network_name: "{{ myvnetname }}"
      name: default

