---
- name: install and start apache
  hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: latest

  - name: latest index.html file is present
    template:
      src: index.html
      dest: /var/www/html/

  - name: httpd is started
    service:
      name: httpd
      state: started

  - name: permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: enabled      

  - name: permit traffic in default zone for http service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled      