---
- name: install and start apache
  hosts: web
  become: true
  gather_facts: true

  tasks:
  - name: httpd package is present
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: latest index.html file is present
    template:
      src: index.html
      dest: /var/www/html/

  - name: httpd is started
    service:
      name: httpd
      state: started

  - name: firewalld package is present
    yum:
      name: httpd
      state: latest
      
  - name: firewalld is started
    service:
      name: firewalld
      state: started

  - name: permit traffic in default zone for https service
    firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: enabled
      

  - name: permit traffic in default zone for http service
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled


  