---
- name: "Send slack message"
  gather_facts: false
  hosts: localhost
  tasks:
  - name: "Send slack message"
    community.general.slack:
      token: T01DW2WQ2NM/B01LEJL8P60/ZlCoRFrR6oL6Mk2njcDVyFMX
      msg: "{{ message }}"
    become: false
    check_mode: false
    run_once: true
