---
- name: Manage vnet address space
  hosts: localhost
  tasks:
        
  - name: Modify existing virtual network adress space
    azure_rm_virtualnetwork:
      resource_group: ansiblelab4amelie
      name: testvn001-ansible
      address_prefixes: "{{ subnet }}/{{ mask }}"
    register: address_prefixes

  - debug:
      var: address_prefixes